### ISSUE TITLE
Serie Routes View

### ISSUE THREAD

**Issue by Zama15** [BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final#71]
### REQUIREMENTS / DESCRIPTION

As a **user**, I want to view a series of routines, where each routine is represented as a separate route. Each routine route should display a title indicating the name of the routine, followed by a series of tables. Each table should contain the name of a series and its corresponding details.

#### Functionalities:

1. **Display Routine Name:**
   - Each routine route should prominently display the name of the routine at the top.

2. **Series Tables:**
   - For each routine, a series of tables should be displayed.
   - Each table should contain the name of a series and its corresponding details.

3. **Consolidated View:**
   - All series within a routine should be displayed on the same page.
   - Users can easily navigate between different routines by accessing their respective routes.

#### User Interaction:

- **Navigating Routines:**
  - Users can access different routines by navigating to their respective routes.
  - Each routine route will display the corresponding series of that routine.

- **Viewing Series Details:**
  - Users can view the details of each series within a routine by examining the corresponding tables.
  - Series details should include relevant information such as name, duration, repetitions, etc.

#### Design Considerations:

- The routine name should be prominently displayed to provide context to the user.
- Tables should be well-organized and visually appealing, making it easy for users to scan through series details.
- Consider using responsive design to ensure optimal viewing experience across devices.

#### Implementation Notes:

- Utilize HTML, CSS, and JavaScript to create the view for routine routes.
- Implement dynamic rendering to display series details based on the selected routine.
- Ensure consistent styling and layout across all routine routes for a cohesive user experience.

### Expected result
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/112733483/3ccbf204-e413-47a8-8b3e-d74c1a15c8c6)

**Comment by angel23v** [comment]
First mistake, you should fix your assignees
