### ISSUE TITLE
Implement devise gem

### ISSUE THREAD

**Issue by etormasa** [BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final#8]
## REQUIREMENTS / DESCRIPTION
 implement devise gem to the project

 generate views 
-  Log in
- Autentication

**Comment by BlazeDex** [comment]
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/73453092/a008d0b7-f226-49e3-b04b-1aac0862a766)
